import type { Metadata } from "next";
import { Oxanium, Lato } from 'next/font/google';
import "./globals.css";
export const oxanium = Oxanium({ subsets: ['latin'], display: 'swap', variable: '--font-oxanium', });

export const lato = Lato({ subsets: ['latin'], weight: ['100', '300', '400', '700', '900'], display: 'swap', variable: '--font-lato', });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

        <body
        className={`${oxanium.variable} ${lato.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}