[package]
name = "betting_contract"
version = "1.0.0"

[addresses]
betting_contract = "_"

[dev-addresses]
betting_contract = "0x42"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"